plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://reasoning-machine.github.io
baseurl: /qrog

title: Reasoning Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Reasoning-Machine
  verb: Reasoning
  instructions_file: reasoning.md
  token: qrog
  server: https://localhost:443
  apiUrl: https://api.groq.com/openai/v1/chat/completions
  fallback_llm: llama-3.3-70b-versatile

app:
  worker_name: qrogapi.js

lm:
  model: moonshotai/kimi-k2-instruct
  max_completion_tokens: 16384
  presence_penalty: 0.0
  temperature: 1.0
  top_p: 0.95


github_settings:
  owner: reasoning-machine
  repo: reasoning_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
